import { Hospital } from '@/types';

export const SAMPLE_HOSPITALS: Hospital[] = [
  {
    _id: 'hosp-001',
    name: 'Apollo City Medical Centre',
    description: 'A premier multi-specialty hospital offering comprehensive emergency and critical care services with state-of-the-art facilities and round-the-clock specialist availability.',
    address: '14 Rajiv Gandhi Marg, Sector 12',
    city: 'Delhi',
    state: 'Delhi',
    pincode: '110001',
    latitude: 28.6139,
    longitude: 77.2090,
    phone: '011-4000-1000',
    emergencyPhone: '011-4000-9999',
    email: 'emergency@apollocity.example',
    hospitalType: 'multispecialty',
    emergencyStatus: 'active',
    beds: { total: 450, available: 62 },
    icu: { total: 60, available: 8 },
    equipment: {
      ventilator: true, ctScan: true, mri: true, xray: true,
      ecg: true, defibrillator: true, dialysis: true,
      oxygen: true, bloodBank: true, operationTheater: true,
    },
    specialists: {
      cardiologist: true, neurologist: true, orthopedic: true,
      pulmonologist: true, pediatrician: true, traumaSurgeon: true,
      generalSurgeon: true, anesthesiologist: true, radiologist: true,
      intensivist: true, burnSpecialist: false, ophthalmologist: true,
    },
    ambulance: true,
    is24x7: true,
    lastUpdated: new Date(Date.now() - 15 * 60000).toISOString(),
    createdAt: new Date().toISOString(),
    rating: 4.7,
    establishedYear: 1995,
    accreditation: 'NABH',
  },
  {
    _id: 'hosp-002',
    name: 'Fortis Trauma & Emergency Hospital',
    description: 'Specialized trauma and emergency facility with dedicated trauma bays, neurology suite, and one of the largest ICU units in the region.',
    address: '8 Emergency Road, Block A',
    city: 'Delhi',
    state: 'Delhi',
    pincode: '110003',
    latitude: 28.6200,
    longitude: 77.2200,
    phone: '011-5000-2000',
    emergencyPhone: '011-5000-1111',
    email: 'trauma@fortis.example',
    hospitalType: 'multispecialty',
    emergencyStatus: 'active',
    beds: { total: 380, available: 45 },
    icu: { total: 80, available: 12 },
    equipment: {
      ventilator: true, ctScan: true, mri: true, xray: true,
      ecg: true, defibrillator: true, dialysis: false,
      oxygen: true, bloodBank: true, operationTheater: true,
    },
    specialists: {
      cardiologist: true, neurologist: true, orthopedic: true,
      pulmonologist: false, pediatrician: true, traumaSurgeon: true,
      generalSurgeon: true, anesthesiologist: true, radiologist: true,
      intensivist: true, burnSpecialist: true, ophthalmologist: false,
    },
    ambulance: true,
    is24x7: true,
    lastUpdated: new Date(Date.now() - 5 * 60000).toISOString(),
    createdAt: new Date().toISOString(),
    rating: 4.5,
    establishedYear: 2003,
    accreditation: 'NABH',
  },
  {
    _id: 'hosp-003',
    name: 'City Cardiac Care Institute',
    description: 'A dedicated cardiac specialty hospital with advanced catheterization labs, cardiac ICU and full cardiac surgery capabilities.',
    address: '22 Heart Avenue, Lajpat Nagar',
    city: 'Delhi',
    state: 'Delhi',
    pincode: '110024',
    latitude: 28.5700,
    longitude: 77.2400,
    phone: '011-6100-3000',
    emergencyPhone: '011-6100-8888',
    email: 'care@citycardiac.example',
    hospitalType: 'specialty',
    emergencyStatus: 'active',
    beds: { total: 200, available: 25 },
    icu: { total: 40, available: 5 },
    equipment: {
      ventilator: true, ctScan: true, mri: false, xray: true,
      ecg: true, defibrillator: true, dialysis: false,
      oxygen: true, bloodBank: true, operationTheater: true,
    },
    specialists: {
      cardiologist: true, neurologist: false, orthopedic: false,
      pulmonologist: true, pediatrician: false, traumaSurgeon: false,
      generalSurgeon: true, anesthesiologist: true, radiologist: true,
      intensivist: true, burnSpecialist: false, ophthalmologist: false,
    },
    ambulance: true,
    is24x7: true,
    lastUpdated: new Date(Date.now() - 30 * 60000).toISOString(),
    createdAt: new Date().toISOString(),
    rating: 4.8,
    establishedYear: 2008,
    accreditation: 'JCI',
  },
  {
    _id: 'hosp-004',
    name: 'Government General Hospital',
    description: 'One of the largest public hospitals serving the region with comprehensive emergency services, affordable care and round-the-clock emergency department.',
    address: '1 Hospital Road, Central District',
    city: 'Delhi',
    state: 'Delhi',
    pincode: '110006',
    latitude: 28.6400,
    longitude: 77.1900,
    phone: '011-2300-4000',
    emergencyPhone: '011-2300-0000',
    email: 'general@govthospital.example',
    hospitalType: 'government',
    emergencyStatus: 'active',
    beds: { total: 1200, available: 180 },
    icu: { total: 100, available: 20 },
    equipment: {
      ventilator: true, ctScan: true, mri: true, xray: true,
      ecg: true, defibrillator: true, dialysis: true,
      oxygen: true, bloodBank: true, operationTheater: true,
    },
    specialists: {
      cardiologist: true, neurologist: true, orthopedic: true,
      pulmonologist: true, pediatrician: true, traumaSurgeon: true,
      generalSurgeon: true, anesthesiologist: true, radiologist: true,
      intensivist: true, burnSpecialist: true, ophthalmologist: true,
    },
    ambulance: true,
    is24x7: true,
    lastUpdated: new Date(Date.now() - 2 * 3600000).toISOString(),
    createdAt: new Date().toISOString(),
    rating: 3.9,
    establishedYear: 1962,
    accreditation: 'NABH',
  },
  {
    _id: 'hosp-005',
    name: 'Max Children\'s & Pediatric Centre',
    description: 'Specialized pediatric hospital with dedicated PICU, neonatal ICU and child-friendly emergency department staffed by expert pediatricians.',
    address: '56 Children\'s Way, South Extension',
    city: 'Delhi',
    state: 'Delhi',
    pincode: '110049',
    latitude: 28.5500,
    longitude: 77.2100,
    phone: '011-4700-5000',
    emergencyPhone: '011-4700-7777',
    email: 'pediatric@maxchildren.example',
    hospitalType: 'specialty',
    emergencyStatus: 'active',
    beds: { total: 250, available: 38 },
    icu: { total: 35, available: 6 },
    equipment: {
      ventilator: true, ctScan: true, mri: true, xray: true,
      ecg: true, defibrillator: true, dialysis: false,
      oxygen: true, bloodBank: true, operationTheater: true,
    },
    specialists: {
      cardiologist: false, neurologist: true, orthopedic: false,
      pulmonologist: true, pediatrician: true, traumaSurgeon: false,
      generalSurgeon: true, anesthesiologist: true, radiologist: true,
      intensivist: true, burnSpecialist: false, ophthalmologist: false,
    },
    ambulance: true,
    is24x7: true,
    lastUpdated: new Date(Date.now() - 45 * 60000).toISOString(),
    createdAt: new Date().toISOString(),
    rating: 4.6,
    establishedYear: 2012,
    accreditation: 'NABH',
  },
  {
    _id: 'hosp-006',
    name: 'Sunrise Neuro & Spine Centre',
    description: 'Premier neurosciences hospital specializing in brain, spine and nervous system conditions with advanced neurosurgery and neuro-ICU facilities.',
    address: '33 Neurology Complex, Vasant Kunj',
    city: 'Delhi',
    state: 'Delhi',
    pincode: '110070',
    latitude: 28.5200,
    longitude: 77.1500,
    phone: '011-3500-6000',
    emergencyPhone: '011-3500-2222',
    email: 'neuro@sunriseneuro.example',
    hospitalType: 'specialty',
    emergencyStatus: 'active',
    beds: { total: 180, available: 15 },
    icu: { total: 30, available: 3 },
    equipment: {
      ventilator: true, ctScan: true, mri: true, xray: true,
      ecg: true, defibrillator: false, dialysis: false,
      oxygen: true, bloodBank: false, operationTheater: true,
    },
    specialists: {
      cardiologist: false, neurologist: true, orthopedic: false,
      pulmonologist: false, pediatrician: false, traumaSurgeon: false,
      generalSurgeon: false, anesthesiologist: true, radiologist: true,
      intensivist: true, burnSpecialist: false, ophthalmologist: false,
    },
    ambulance: true,
    is24x7: true,
    lastUpdated: new Date(Date.now() - 20 * 60000).toISOString(),
    createdAt: new Date().toISOString(),
    rating: 4.7,
    establishedYear: 2010,
    accreditation: 'NABH',
  },
  {
    _id: 'hosp-007',
    name: 'Medanta Burns & Plastics Unit',
    description: 'Dedicated burn and plastic surgery facility with specialized burn ICU, skin grafting capabilities and wound care specialists.',
    address: '9 Burns Treatment Road, Dwarka',
    city: 'Delhi',
    state: 'Delhi',
    pincode: '110075',
    latitude: 28.5700,
    longitude: 77.0300,
    phone: '011-4200-7000',
    emergencyPhone: '011-4200-3333',
    email: 'burns@medantaburns.example',
    hospitalType: 'specialty',
    emergencyStatus: 'limited',
    beds: { total: 120, available: 8 },
    icu: { total: 20, available: 2 },
    equipment: {
      ventilator: true, ctScan: false, mri: false, xray: true,
      ecg: true, defibrillator: false, dialysis: false,
      oxygen: true, bloodBank: true, operationTheater: true,
    },
    specialists: {
      cardiologist: false, neurologist: false, orthopedic: false,
      pulmonologist: false, pediatrician: false, traumaSurgeon: false,
      generalSurgeon: true, anesthesiologist: true, radiologist: false,
      intensivist: true, burnSpecialist: true, ophthalmologist: false,
    },
    ambulance: false,
    is24x7: true,
    lastUpdated: new Date(Date.now() - 3 * 3600000).toISOString(),
    createdAt: new Date().toISOString(),
    rating: 4.3,
    establishedYear: 2015,
    accreditation: 'NABH',
  },
  {
    _id: 'hosp-008',
    name: 'HealthCity Multispecialty Hospital',
    description: 'A modern multi-specialty hospital offering a wide range of emergency and elective services with experienced medical professionals and modern infrastructure.',
    address: '77 Health City Boulevard, Rohini',
    city: 'Delhi',
    state: 'Delhi',
    pincode: '110085',
    latitude: 28.7300,
    longitude: 77.1200,
    phone: '011-5500-8000',
    emergencyPhone: '011-5500-4444',
    email: 'emergency@healthcity.example',
    hospitalType: 'multispecialty',
    emergencyStatus: 'active',
    beds: { total: 320, available: 55 },
    icu: { total: 45, available: 9 },
    equipment: {
      ventilator: true, ctScan: true, mri: true, xray: true,
      ecg: true, defibrillator: true, dialysis: true,
      oxygen: true, bloodBank: true, operationTheater: true,
    },
    specialists: {
      cardiologist: true, neurologist: false, orthopedic: true,
      pulmonologist: true, pediatrician: true, traumaSurgeon: true,
      generalSurgeon: true, anesthesiologist: true, radiologist: true,
      intensivist: true, burnSpecialist: false, ophthalmologist: true,
    },
    ambulance: true,
    is24x7: true,
    lastUpdated: new Date(Date.now() - 10 * 60000).toISOString(),
    createdAt: new Date().toISOString(),
    rating: 4.4,
    establishedYear: 2007,
    accreditation: 'NABH',
  },
  {
    _id: 'hosp-009',
    name: 'Primus Ortho & Trauma Centre',
    description: 'Specialized orthopedic and trauma hospital with advanced joint replacement unit, dedicated trauma bay and 24-hour orthopedic emergency services.',
    address: '45 Ortho Lane, Saket',
    city: 'Delhi',
    state: 'Delhi',
    pincode: '110017',
    latitude: 28.5299,
    longitude: 77.2134,
    phone: '011-4600-9000',
    emergencyPhone: '011-4600-5555',
    email: 'trauma@primusortho.example',
    hospitalType: 'specialty',
    emergencyStatus: 'active',
    beds: { total: 160, available: 22 },
    icu: { total: 25, available: 4 },
    equipment: {
      ventilator: false, ctScan: true, mri: true, xray: true,
      ecg: true, defibrillator: false, dialysis: false,
      oxygen: true, bloodBank: true, operationTheater: true,
    },
    specialists: {
      cardiologist: false, neurologist: false, orthopedic: true,
      pulmonologist: false, pediatrician: false, traumaSurgeon: true,
      generalSurgeon: true, anesthesiologist: true, radiologist: true,
      intensivist: false, burnSpecialist: false, ophthalmologist: false,
    },
    ambulance: true,
    is24x7: true,
    lastUpdated: new Date(Date.now() - 25 * 60000).toISOString(),
    createdAt: new Date().toISOString(),
    rating: 4.5,
    establishedYear: 2011,
    accreditation: 'NABH',
  },
  {
    _id: 'hosp-010',
    name: 'Nandini Community Health Centre',
    description: 'A community-level hospital providing essential emergency services, outpatient care and basic inpatient facilities for the local population.',
    address: '12 Community Centre Road, Mayur Vihar',
    city: 'Delhi',
    state: 'Delhi',
    pincode: '110091',
    latitude: 28.6100,
    longitude: 77.3000,
    phone: '011-2200-0001',
    emergencyPhone: '011-2200-0002',
    email: 'help@nandinihospital.example',
    hospitalType: 'trust',
    emergencyStatus: 'limited',
    beds: { total: 80, available: 14 },
    icu: { total: 8, available: 0 },
    equipment: {
      ventilator: false, ctScan: false, mri: false, xray: true,
      ecg: true, defibrillator: true, dialysis: false,
      oxygen: true, bloodBank: false, operationTheater: true,
    },
    specialists: {
      cardiologist: false, neurologist: false, orthopedic: false,
      pulmonologist: false, pediatrician: true, traumaSurgeon: false,
      generalSurgeon: true, anesthesiologist: true, radiologist: false,
      intensivist: false, burnSpecialist: false, ophthalmologist: false,
    },
    ambulance: true,
    is24x7: false,
    lastUpdated: new Date(Date.now() - 6 * 3600000).toISOString(),
    createdAt: new Date().toISOString(),
    rating: 3.7,
    establishedYear: 1998,
  },
];
